version: "3.7"
services:
  runner1:
    build:
      context: .
      dockerfile: Dockerfile
    image: localrunner:latest
    environment:
      #ORGANIZATION: ${ORGANIZATION}
      REG_TOKEN: ${REG_TOKEN}
      ACCESS_TOKEN: ${ACCESS_TOKEN}
      REPO: ${REPO}
      OWNER: ${OWNER}
    container_name: github-runner-localrunner1
    # hostname: ${DOCKERHOST_NAME}-localrunner1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/local/bin/docker
        # - kwati-runner1:/home/runner

  runner2:
   build:
     context: .
     dockerfile: Dockerfile
   image: localrunner:latest
   #image: dockerhub.khalti.office:5000/github-runner-kwati/runner:latest
   environment:
     #ORGANIZATION: ${ORGANIZATION}
     REG_TOKEN: ${REG_TOKEN}
     ACCESS_TOKEN: ${ACCESS_TOKEN}
     REPO: ${REPO}
     OWNER: ${OWNER}
   container_name: github-runner-localrunner2
   #hostname: ${DOCKERHOST_NAME}-localrunner2
   volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - /usr/bin/docker:/usr/local/bin/docker
       # - kwati-runner2:/home/runner
       
  runner3:
   build:
     context: .
     dockerfile: Dockerfile
   image: localrunner:latest
   # image: dockerhub.khalti.office:5000/github-runner-kwati/runner:latest
   environment:
     #ORGANIZATION: ${ORGANIZATION}
     REG_TOKEN: ${REG_TOKEN}
     ACCESS_TOKEN: ${ACCESS_TOKEN}
     REPO: ${REPO}
     OWNER: ${OWNER}
   container_name: github-runner-localrunner3
   #hostname: ${DOCKERHOST_NAME}-localrunner3
   volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - /usr/bin/docker:/usr/local/bin/docker
       #- kwati-runner3:/home/runner      

  runner4:
   build:
     context: .
     dockerfile: Dockerfile
   image: localrunner:latest
   #image: dockerhub.khalti.office:5000/github-runner-kwati/runner:latest
   environment:
   #ORGANIZATION: ${ORGANIZATION}
     REG_TOKEN: ${REG_TOKEN}
     ACCESS_TOKEN: ${ACCESS_TOKEN}
     REPO: ${REPO}
     OWNER: ${OWNER}
   container_name: github-runner-localrunner4
   #hostname: ${DOCKERHOST_NAME}-localrunner4
   volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - /usr/bin/docker:/usr/local/bin/docker
       # - kwati-runner4:/home/runner

volumes:
  localrunner1:
    external: false
  localrunner2:
    external: false
  localrunner3:
    external: false
  localrunner4:
    external: false